# Generated by Django 5.1.6 on 2025-03-21 21:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotroca', '0003_alter_livro_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensagem',
            name='livro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='bibliotroca.livro'),
        ),
        migrations.AlterField(
            model_name='mensagem',
            name='usuario_destinatario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens_recebidas_publicas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mensagem',
            name='usuario_remetente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens_enviadas_publicas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='MensagemPrivada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.TextField()),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens_privadas_recebidas', to=settings.AUTH_USER_MODEL)),
                ('remetente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens_privadas_enviadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
