# Generated by Django 5.1.6 on 2025-03-22 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotroca', '0004_alter_mensagem_livro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensagemprivada',
            name='lida',
            field=models.BooleanField(default=False),
        ),
    ]
