# Generated by Django 5.1.6 on 2025-03-22 11:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotroca', '0005_mensagemprivada_lida'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensagemprivada',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
